version: "3"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - mssql
    mssql:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"